apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-user
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-user
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podreader-user
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default